services:
  - type: web
    name: betterbeing-web
    env: node
    plan: free
    region: oregon
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NEXT_PUBLIC_STACK_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
        sync: false
      - key: STACK_SECRET_SERVER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
